#!/usr/bin/env python3
import sys
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPT_PATH = os.path.join(BASE_DIR, "app", "automation.py")

def main():
    if len(sys.argv) > 1 and sys.argv[1] in ["s", "start"]:
        os.system(f"python {SCRIPT_PATH}")
    else:
        print("Usage: krpa start (or krpa s)")

if __name__ == "__main__":
    main()

